const PROFILES = {
  ADMINISTRADOR: 'ADMINISTRADOR',
  CENTRAL_VAGAS: 'CENTRAL_VAGAS',
  CRAS: 'CRAS',
  CREAS: 'CREAS',
  OSC: 'OSC',
  CIDADAO: 'CIDADAO'
};

const MANAGEMENT_PROFILES = [
  PROFILES.ADMINISTRADOR,
  PROFILES.CENTRAL_VAGAS,
  PROFILES.CRAS,
  PROFILES.CREAS,
  PROFILES.OSC
];

module.exports = { PROFILES, MANAGEMENT_PROFILES };
