const PROFILES = {
  ADMINISTRADOR: 'ADMINISTRADOR',
  GESTOR_CENTRAL: 'GESTOR_CENTRAL',
  FUNCIONARIO_CRAS: 'FUNCIONARIO_CRAS',
  FUNCIONARIO_CREAS: 'FUNCIONARIO_CREAS',
  CENTRAL_VAGAS: 'CENTRAL_VAGAS',
  CRAS: 'CRAS',
  CREAS: 'CREAS',
  OSC: 'OSC',
  CIDADAO: 'CIDADAO'
};

const CENTRAL_PROFILES = [
  PROFILES.ADMINISTRADOR,
  PROFILES.GESTOR_CENTRAL,
  PROFILES.CENTRAL_VAGAS
];

const CRAS_PROFILES = [
  PROFILES.ADMINISTRADOR,
  PROFILES.GESTOR_CENTRAL,
  PROFILES.FUNCIONARIO_CRAS,
  PROFILES.CRAS,
  PROFILES.CENTRAL_VAGAS
];

const CREAS_PROFILES = [
  PROFILES.ADMINISTRADOR,
  PROFILES.GESTOR_CENTRAL,
  PROFILES.FUNCIONARIO_CREAS,
  PROFILES.CREAS,
  PROFILES.CENTRAL_VAGAS
];

const MANAGEMENT_PROFILES = [
  PROFILES.ADMINISTRADOR,
  PROFILES.GESTOR_CENTRAL,
  PROFILES.FUNCIONARIO_CRAS,
  PROFILES.FUNCIONARIO_CREAS,
  PROFILES.CENTRAL_VAGAS,
  PROFILES.CRAS,
  PROFILES.CREAS,
  PROFILES.OSC
];

module.exports = { PROFILES, CENTRAL_PROFILES, CRAS_PROFILES, CREAS_PROFILES, MANAGEMENT_PROFILES };
